/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.alex.dcc025.gui;

import java.util.ArrayList;
import java.util.List;

import javax.swing.DefaultListModel;
import javax.swing.ListModel;

import com.alex.dcc025.Sistema;
import com.alex.dcc025.franquia.Franquia;
import com.alex.dcc025.franquia.pedido.Pedido;
import com.alex.dcc025.franquia.pedido.Produto;
import com.alex.dcc025.franquia.solicitacao.Solicitacao;
import com.alex.dcc025.usuario.Usuario;
import com.alex.dcc025.usuario.usuario.Dono;
import com.alex.dcc025.usuario.usuario.Gerente;
import com.alex.dcc025.usuario.usuario.Vendedor;

import java.util.Locale;
import javax.swing.JLabel;

/**
 *
 * @author SUPERVISOR
 */
public class TelaGerente extends javax.swing.JPanel {

    private final Sistema sistema;
    private final Gerente usuario;
    private final GUI janela;
    
    /**
     * Creates new form TelaDono
     */
    public TelaGerente(Sistema sistema, Gerente usuario, GUI janela) {
        this.sistema = sistema;
        this.usuario = usuario;
        this.janela = janela;
        initComponents();


        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        informacoesPanel = new javax.swing.JPanel();
        logadoComoLabel = new javax.swing.JLabel();
        nomeUsuarioLabel = new javax.swing.JLabel();
        gerentesPanel = new javax.swing.JPanel();
        gerentesLabel = new javax.swing.JLabel();
        gerentesScroll = new javax.swing.JScrollPane();
        vendedoresList = new javax.swing.JList<>();
        editarGerenteButton = new javax.swing.JButton();
        adicionarGerenteButton = new javax.swing.JButton();
        excluirGerenteButton = new javax.swing.JButton();
        gerentesPanel1 = new javax.swing.JPanel();
        gerentesLabel1 = new javax.swing.JLabel();
        gerentesScroll1 = new javax.swing.JScrollPane();
        vendedoresList1 = new javax.swing.JList<>();
        editarGerenteButton1 = new javax.swing.JButton();
        adicionarGerenteButton1 = new javax.swing.JButton();
        excluirGerenteButton1 = new javax.swing.JButton();
        gerentesPanel2 = new javax.swing.JPanel();
        gerentesLabel2 = new javax.swing.JLabel();
        gerentesScroll2 = new javax.swing.JScrollPane();
        vendedoresList2 = new javax.swing.JList<>();
        adicionarGerenteButton2 = new javax.swing.JButton();
        excluirGerenteButton2 = new javax.swing.JButton();
        gerentesPanel3 = new javax.swing.JPanel();
        gerentesLabel3 = new javax.swing.JLabel();
        gerentesScroll3 = new javax.swing.JScrollPane();
        vendedoresList3 = new javax.swing.JList<>();
        editarGerenteButton2 = new javax.swing.JButton();
        excluirGerenteButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        rankingPanel = new javax.swing.JPanel();
        rankingScrollPane = new javax.swing.JScrollPane();
        ranking = new javax.swing.JPanel();
        rankingLabel = new javax.swing.JLabel();
        porVolume = new javax.swing.JRadioButton();
        porValor = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        rankingLabel1 = new javax.swing.JLabel();
        rankingScrollPane1 = new javax.swing.JScrollPane();
        ranking1 = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        buttonGroup1.add(porVolume);
        buttonGroup1.add(porValor);

        setPreferredSize(new java.awt.Dimension(1280, 720));

        logadoComoLabel.setText("Logado como:");

        nomeUsuarioLabel.setText(String.format("%s (%s)", usuario.getNome(), usuario.getClass().getSimpleName())
        );

        javax.swing.GroupLayout informacoesPanelLayout = new javax.swing.GroupLayout(informacoesPanel);
        informacoesPanel.setLayout(informacoesPanelLayout);
        informacoesPanelLayout.setHorizontalGroup(
            informacoesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informacoesPanelLayout.createSequentialGroup()
                .addComponent(logadoComoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeUsuarioLabel)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        informacoesPanelLayout.setVerticalGroup(
            informacoesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, informacoesPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(informacoesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logadoComoLabel)
                    .addComponent(nomeUsuarioLabel))
                .addGap(28, 28, 28))
        );

        gerentesLabel.setText("Vendedores");

        vendedoresList.setModel(new MeuListModel<Vendedor>(usuario.getFranquia() != null ? usuario.getFranquia().getVendedores() : new ArrayList<>()));
        gerentesScroll.setViewportView(vendedoresList);

        editarGerenteButton.setText("Editar");
        editarGerenteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarGerenteButtonActionPerformed(evt);
            }
        });

        adicionarGerenteButton.setText("Adicionar");
        adicionarGerenteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarGerenteButtonActionPerformed(evt);
            }
        });

        excluirGerenteButton.setText("Excluir");
        excluirGerenteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirGerenteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gerentesPanelLayout = new javax.swing.GroupLayout(gerentesPanel);
        gerentesPanel.setLayout(gerentesPanelLayout);
        gerentesPanelLayout.setHorizontalGroup(
            gerentesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gerentesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(gerentesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gerentesScroll, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                    .addGroup(gerentesPanelLayout.createSequentialGroup()
                        .addGroup(gerentesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gerentesLabel)
                            .addGroup(gerentesPanelLayout.createSequentialGroup()
                                .addComponent(excluirGerenteButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(editarGerenteButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(adicionarGerenteButton)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        gerentesPanelLayout.setVerticalGroup(
            gerentesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gerentesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gerentesLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gerentesScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gerentesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editarGerenteButton)
                    .addComponent(adicionarGerenteButton)
                    .addComponent(excluirGerenteButton))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        gerentesLabel1.setText("Produtos");

        vendedoresList1.setModel(new MeuListModel<Produto>(usuario.getFranquia().getEstoque().keySet().stream().toList()));
        gerentesScroll1.setViewportView(vendedoresList1);

        editarGerenteButton1.setText("Editar");
        editarGerenteButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarGerenteButton1ActionPerformed(evt);
            }
        });

        adicionarGerenteButton1.setText("Adicionar");
        adicionarGerenteButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarGerenteButton1ActionPerformed(evt);
            }
        });

        excluirGerenteButton1.setText("Excluir");
        excluirGerenteButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirGerenteButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gerentesPanel1Layout = new javax.swing.GroupLayout(gerentesPanel1);
        gerentesPanel1.setLayout(gerentesPanel1Layout);
        gerentesPanel1Layout.setHorizontalGroup(
            gerentesPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gerentesPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(gerentesPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gerentesScroll1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE)
                    .addGroup(gerentesPanel1Layout.createSequentialGroup()
                        .addGroup(gerentesPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gerentesLabel1)
                            .addGroup(gerentesPanel1Layout.createSequentialGroup()
                                .addComponent(excluirGerenteButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(editarGerenteButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(adicionarGerenteButton1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        gerentesPanel1Layout.setVerticalGroup(
            gerentesPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gerentesPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gerentesLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gerentesScroll1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gerentesPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editarGerenteButton1)
                    .addComponent(adicionarGerenteButton1)
                    .addComponent(excluirGerenteButton1))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        gerentesLabel2.setText("Solicitações");

        vendedoresList2.setModel(new MeuListModel<Solicitacao>(usuario.getSolicitacoes()));
        gerentesScroll2.setViewportView(vendedoresList2);

        adicionarGerenteButton2.setText("Aceitar");
        adicionarGerenteButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarGerenteButton2ActionPerformed(evt);
            }
        });

        excluirGerenteButton2.setText("Recusar");
        excluirGerenteButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirGerenteButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gerentesPanel2Layout = new javax.swing.GroupLayout(gerentesPanel2);
        gerentesPanel2.setLayout(gerentesPanel2Layout);
        gerentesPanel2Layout.setHorizontalGroup(
            gerentesPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gerentesPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(gerentesPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gerentesScroll2)
                    .addGroup(gerentesPanel2Layout.createSequentialGroup()
                        .addGroup(gerentesPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gerentesLabel2)
                            .addGroup(gerentesPanel2Layout.createSequentialGroup()
                                .addComponent(excluirGerenteButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(adicionarGerenteButton2)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        gerentesPanel2Layout.setVerticalGroup(
            gerentesPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gerentesPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gerentesLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gerentesScroll2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gerentesPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adicionarGerenteButton2)
                    .addComponent(excluirGerenteButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gerentesLabel3.setText("Pedidos");

        vendedoresList3.setModel(new MeuListModel<Pedido>(usuario.getFranquia().getPedidos()));
        gerentesScroll3.setViewportView(vendedoresList3);

        editarGerenteButton2.setText("Editar");
        editarGerenteButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarGerenteButton2ActionPerformed(evt);
            }
        });

        excluirGerenteButton3.setText("Excluir");
        excluirGerenteButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirGerenteButton3ActionPerformed(evt);
            }
        });

        jButton1.setText("Visualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gerentesPanel3Layout = new javax.swing.GroupLayout(gerentesPanel3);
        gerentesPanel3.setLayout(gerentesPanel3Layout);
        gerentesPanel3Layout.setHorizontalGroup(
            gerentesPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gerentesPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(gerentesPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gerentesScroll3, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gerentesLabel3)
                    .addGroup(gerentesPanel3Layout.createSequentialGroup()
                        .addComponent(excluirGerenteButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editarGerenteButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        gerentesPanel3Layout.setVerticalGroup(
            gerentesPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gerentesPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gerentesLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gerentesScroll3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gerentesPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editarGerenteButton2)
                    .addComponent(excluirGerenteButton3)
                    .addComponent(jButton1))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        rankingPanel.setPreferredSize(new java.awt.Dimension(308, 238));

        ranking.setLayout(new java.awt.GridLayout(0, 1));
        rankingScrollPane.setViewportView(ranking);

        rankingLabel.setText("Ranking de Vendedores");

        porVolume.setText("Por volume");
        porVolume.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                porVolumeActionPerformed(evt);
            }
        });

        porValor.setText("Por valor");
        porValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                porValorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rankingPanelLayout = new javax.swing.GroupLayout(rankingPanel);
        rankingPanel.setLayout(rankingPanelLayout);
        rankingPanelLayout.setHorizontalGroup(
            rankingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rankingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rankingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rankingLabel)
                    .addComponent(rankingScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(rankingPanelLayout.createSequentialGroup()
                        .addComponent(porVolume)
                        .addGap(5, 5, 5)
                        .addComponent(porValor)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        rankingPanelLayout.setVerticalGroup(
            rankingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, rankingPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rankingLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rankingScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(rankingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(porValor)
                    .addComponent(porVolume))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rankingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rankingPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        rankingLabel1.setText("Itens em baixa");

        ranking1.setLayout(new java.awt.GridLayout(0, 1));
        rankingScrollPane1.setViewportView(ranking1);
        List<Produto> produtosBaixa = usuario.getFranquia().getEstoque().keySet().stream().filter(p -> usuario.getFranquia().isEstoqueBaixo(p)).toList();

        for (Produto produto : produtosBaixa) {
            ranking1.add(new JLabel(produto.toString()));
        }

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rankingLabel1)
                    .addComponent(rankingScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rankingLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rankingScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(informacoesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gerentesPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gerentesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(gerentesPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(gerentesPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(120, 120, 120)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(informacoesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(136, 136, 136)
                        .addComponent(gerentesPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gerentesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addComponent(gerentesPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addComponent(gerentesPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)))
                .addContainerGap(135, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void editarGerenteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarGerenteButtonActionPerformed
        if(vendedoresList.getSelectedValue() == null) return;
        
        janela.mudarTela(new TelaEditarVendedor(sistema, usuario, janela, vendedoresList.getSelectedValue()));
    }//GEN-LAST:event_editarGerenteButtonActionPerformed

    private void adicionarGerenteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarGerenteButtonActionPerformed
        janela.mudarTela(new TelaAdicionarVendedor(sistema, usuario, janela));
    }//GEN-LAST:event_adicionarGerenteButtonActionPerformed

    private void excluirGerenteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirGerenteButtonActionPerformed
        if(vendedoresList.getSelectedValue() == null) return;
        
        usuario.removerVendedor(vendedoresList.getSelectedValue(), sistema);
        
        janela.mudarTela(new TelaGerente(sistema, usuario, janela));
    }//GEN-LAST:event_excluirGerenteButtonActionPerformed

    private void editarGerenteButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarGerenteButton1ActionPerformed
        if(vendedoresList1.getSelectedValue() == null) return;
        
        janela.mudarTela(new TelaEditarProduto(sistema, usuario, janela, vendedoresList1.getSelectedValue()));
    }//GEN-LAST:event_editarGerenteButton1ActionPerformed

    private void adicionarGerenteButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarGerenteButton1ActionPerformed
        janela.mudarTela(new TelaAdicionarProduto(sistema, usuario, janela));
    }//GEN-LAST:event_adicionarGerenteButton1ActionPerformed

    private void excluirGerenteButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirGerenteButton1ActionPerformed
        if(vendedoresList1.getSelectedValue() == null) return;
        
        usuario.removerProduto(vendedoresList1.getSelectedValue());
        
        janela.mudarTela(new TelaGerente(sistema, usuario, janela));
    }//GEN-LAST:event_excluirGerenteButton1ActionPerformed

    private void adicionarGerenteButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarGerenteButton2ActionPerformed
        if(vendedoresList2.getSelectedValue() == null) return;
        
        usuario.aceitarSolicitacao(vendedoresList2.getSelectedValue());
        
        janela.mudarTela(new TelaGerente(sistema, usuario, janela));
    }//GEN-LAST:event_adicionarGerenteButton2ActionPerformed

    private void excluirGerenteButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirGerenteButton2ActionPerformed
        if(vendedoresList2.getSelectedValue() == null) return;
        
        usuario.recusarSolicitacao(vendedoresList2.getSelectedValue());
        
        janela.mudarTela(new TelaGerente(sistema, usuario, janela));
    }//GEN-LAST:event_excluirGerenteButton2ActionPerformed

    private void editarGerenteButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarGerenteButton2ActionPerformed
        if(vendedoresList3.getSelectedValue() == null) return;
        
        janela.mudarTela(new TelaEditarPedido(sistema, usuario, janela, vendedoresList3.getSelectedValue()));
    }//GEN-LAST:event_editarGerenteButton2ActionPerformed

    private void excluirGerenteButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirGerenteButton3ActionPerformed
        if(vendedoresList3.getSelectedValue() == null) return;
        
        usuario.removerPedido(vendedoresList3.getSelectedValue());
        
        janela.mudarTela(new TelaGerente(sistema, usuario, janela));
    }//GEN-LAST:event_excluirGerenteButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(vendedoresList3.getSelectedValue() == null) return;
        
        janela.mudarTela(new TelaVisualizarPedidoGerente(sistema, usuario, janela, vendedoresList3.getSelectedValue()));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void porVolumeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_porVolumeActionPerformed
        ranking.removeAll();

        for (Vendedor vendedor : usuario.getFranquia().getVendedores().stream().sorted((v1, v2) -> v2.getVolume() - v1.getVolume()).toList()) {
            ranking.add(new JLabel(String.format(Locale.getDefault(), "%s - Vendas realizadas: %d - Valor total: R$ %,.2f", vendedor.toString(), vendedor.getVolume(), vendedor.getValor())));
        }

        ranking.revalidate();
        ranking.repaint();
    }//GEN-LAST:event_porVolumeActionPerformed

    private void porValorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_porValorActionPerformed
        ranking.removeAll();

        for (Vendedor vendedor : usuario.getFranquia().getVendedores().stream().sorted((v1, v2) -> (int)(v2.getValor() - v1.getValor())).toList()) {
            ranking.add(new JLabel(String.format(Locale.getDefault(), "%s - Vendas realizadas: %d - Valor total: R$ %,.2f", vendedor.toString(), vendedor.getVolume(), vendedor.getValor())));
        }

        ranking.revalidate();
        ranking.repaint();
    }//GEN-LAST:event_porValorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarGerenteButton;
    private javax.swing.JButton adicionarGerenteButton1;
    private javax.swing.JButton adicionarGerenteButton2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton editarGerenteButton;
    private javax.swing.JButton editarGerenteButton1;
    private javax.swing.JButton editarGerenteButton2;
    private javax.swing.JButton excluirGerenteButton;
    private javax.swing.JButton excluirGerenteButton1;
    private javax.swing.JButton excluirGerenteButton2;
    private javax.swing.JButton excluirGerenteButton3;
    private javax.swing.JLabel gerentesLabel;
    private javax.swing.JLabel gerentesLabel1;
    private javax.swing.JLabel gerentesLabel2;
    private javax.swing.JLabel gerentesLabel3;
    private javax.swing.JPanel gerentesPanel;
    private javax.swing.JPanel gerentesPanel1;
    private javax.swing.JPanel gerentesPanel2;
    private javax.swing.JPanel gerentesPanel3;
    private javax.swing.JScrollPane gerentesScroll;
    private javax.swing.JScrollPane gerentesScroll1;
    private javax.swing.JScrollPane gerentesScroll2;
    private javax.swing.JScrollPane gerentesScroll3;
    private javax.swing.JPanel informacoesPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel logadoComoLabel;
    private javax.swing.JLabel nomeUsuarioLabel;
    private javax.swing.JRadioButton porValor;
    private javax.swing.JRadioButton porVolume;
    private javax.swing.JPanel ranking;
    private javax.swing.JPanel ranking1;
    private javax.swing.JLabel rankingLabel;
    private javax.swing.JLabel rankingLabel1;
    private javax.swing.JPanel rankingPanel;
    private javax.swing.JScrollPane rankingScrollPane;
    private javax.swing.JScrollPane rankingScrollPane1;
    private javax.swing.JList<Vendedor> vendedoresList;
    private javax.swing.JList<Produto> vendedoresList1;
    private javax.swing.JList<Solicitacao> vendedoresList2;
    private javax.swing.JList<Pedido> vendedoresList3;
    // End of variables declaration//GEN-END:variables
}
