/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.alex.dcc025.gui;

import javax.swing.DefaultListModel;
import javax.swing.ListModel;

import com.alex.dcc025.Sistema;
import com.alex.dcc025.franquia.Franquia;
import com.alex.dcc025.usuario.Dono;
import com.alex.dcc025.usuario.Gerente;
import com.alex.dcc025.usuario.Vendedor;
import com.alex.dcc025.usuario.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author SUPERVISOR
 */
public class TelaDono extends javax.swing.JPanel {

    private final Sistema sistema;
    private final Dono usuario;
    private final GUI janela;
    
    /**
     * Creates new form TelaDono
     */
    public TelaDono(Sistema sistema, Dono usuario, GUI janela) {
        this.sistema = sistema;
        this.usuario = usuario;
        this.janela = janela;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        informacoesPanel = new javax.swing.JPanel();
        logadoComoLabel = new javax.swing.JLabel();
        nomeUsuarioLabel = new javax.swing.JLabel();
        franquiasPanel = new javax.swing.JPanel();
        franquiasLabel = new javax.swing.JLabel();
        franquiasScroll = new javax.swing.JScrollPane();
        franquiasList = new javax.swing.JList<>();
        excluirFranquiaButton = new javax.swing.JButton();
        visualizarFranquiaButton = new javax.swing.JButton();
        adicionarFranquiaButton = new javax.swing.JButton();
        editarFranquiaButton = new javax.swing.JButton();
        gerentesPanel = new javax.swing.JPanel();
        gerentesLabel = new javax.swing.JLabel();
        gerentesScroll = new javax.swing.JScrollPane();
        gerentesList = new javax.swing.JList<>();
        editarGerenteButton = new javax.swing.JButton();
        adicionarGerenteButton = new javax.swing.JButton();
        excluirGerenteButton = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setPreferredSize(new java.awt.Dimension(1280, 720));

        logadoComoLabel.setText("Logado como:");

        nomeUsuarioLabel.setText(String.format("%s (%s)", usuario.getNome(), usuario.getClass().getSimpleName())
        );

        javax.swing.GroupLayout informacoesPanelLayout = new javax.swing.GroupLayout(informacoesPanel);
        informacoesPanel.setLayout(informacoesPanelLayout);
        informacoesPanelLayout.setHorizontalGroup(
            informacoesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(informacoesPanelLayout.createSequentialGroup()
                .addComponent(logadoComoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeUsuarioLabel)
                .addContainerGap(63, Short.MAX_VALUE))
        );
        informacoesPanelLayout.setVerticalGroup(
            informacoesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, informacoesPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(informacoesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(logadoComoLabel)
                    .addComponent(nomeUsuarioLabel))
                .addGap(28, 28, 28))
        );

        franquiasLabel.setText("Franquias");

        franquiasList.setModel(new MeuListModel<Franquia>(usuario.getFranquias()));
        franquiasScroll.setViewportView(franquiasList);

        excluirFranquiaButton.setText("Excluir");
        excluirFranquiaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirFranquiaButtonActionPerformed(evt);
            }
        });

        visualizarFranquiaButton.setText("Visualizar");
        visualizarFranquiaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visualizarFranquiaButtonActionPerformed(evt);
            }
        });

        adicionarFranquiaButton.setText("Adicionar");
        adicionarFranquiaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarFranquiaButtonActionPerformed(evt);
            }
        });

        editarFranquiaButton.setText("Mudar gerente");
        editarFranquiaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarFranquiaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout franquiasPanelLayout = new javax.swing.GroupLayout(franquiasPanel);
        franquiasPanel.setLayout(franquiasPanelLayout);
        franquiasPanelLayout.setHorizontalGroup(
            franquiasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(franquiasPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(franquiasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(franquiasScroll, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(franquiasPanelLayout.createSequentialGroup()
                        .addComponent(franquiasLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(franquiasPanelLayout.createSequentialGroup()
                        .addComponent(excluirFranquiaButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(visualizarFranquiaButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editarFranquiaButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(adicionarFranquiaButton)))
                .addContainerGap())
        );
        franquiasPanelLayout.setVerticalGroup(
            franquiasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, franquiasPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(franquiasLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(franquiasScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(franquiasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(excluirFranquiaButton)
                    .addComponent(visualizarFranquiaButton)
                    .addComponent(adicionarFranquiaButton)
                    .addComponent(editarFranquiaButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gerentesLabel.setText("Gerentes");

        gerentesList.setModel(new MeuListModel<Gerente>(usuario.getGerentes()));
        gerentesScroll.setViewportView(gerentesList);

        editarGerenteButton.setText("Editar");
        editarGerenteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarGerenteButtonActionPerformed(evt);
            }
        });

        adicionarGerenteButton.setText("Adicionar");
        adicionarGerenteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adicionarGerenteButtonActionPerformed(evt);
            }
        });

        excluirGerenteButton.setText("Excluir");
        excluirGerenteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirGerenteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gerentesPanelLayout = new javax.swing.GroupLayout(gerentesPanel);
        gerentesPanel.setLayout(gerentesPanelLayout);
        gerentesPanelLayout.setHorizontalGroup(
            gerentesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gerentesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(gerentesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gerentesScroll)
                    .addGroup(gerentesPanelLayout.createSequentialGroup()
                        .addGroup(gerentesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gerentesLabel)
                            .addGroup(gerentesPanelLayout.createSequentialGroup()
                                .addComponent(excluirGerenteButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(editarGerenteButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(adicionarGerenteButton)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        gerentesPanelLayout.setVerticalGroup(
            gerentesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gerentesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(gerentesLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gerentesScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(gerentesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editarGerenteButton)
                    .addComponent(adicionarGerenteButton)
                    .addComponent(excluirGerenteButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(1058, Short.MAX_VALUE)
                        .addComponent(informacoesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(franquiasPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(gerentesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(informacoesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(franquiasPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(gerentesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(184, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void excluirFranquiaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirFranquiaButtonActionPerformed
        if (franquiasList.getSelectedValue() == null) return;
        
        usuario.removerFranquia(franquiasList.getSelectedValue(), sistema);
        janela.mudarTela(new TelaDono(sistema, usuario, janela));
    }//GEN-LAST:event_excluirFranquiaButtonActionPerformed

    private void editarGerenteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarGerenteButtonActionPerformed
        
    }//GEN-LAST:event_editarGerenteButtonActionPerformed

    private void adicionarGerenteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarGerenteButtonActionPerformed
        janela.mudarTela(new TelaAdicionarGerente(sistema, usuario, janela));
    }//GEN-LAST:event_adicionarGerenteButtonActionPerformed

    private void excluirGerenteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirGerenteButtonActionPerformed
        if (gerentesList.getSelectedValue() == null) return;
        
        usuario.removerGerente(gerentesList.getSelectedValue(), sistema);
        janela.mudarTela(new TelaDono(sistema, usuario, janela));
    }//GEN-LAST:event_excluirGerenteButtonActionPerformed

    private void visualizarFranquiaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visualizarFranquiaButtonActionPerformed
        if (franquiasList.getSelectedValue() == null) return;
        
        janela.mudarTela(new TelaVisualizarFranquia(sistema, usuario, janela, franquiasList.getSelectedValue()));
        
    }//GEN-LAST:event_visualizarFranquiaButtonActionPerformed

    private void adicionarFranquiaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adicionarFranquiaButtonActionPerformed
        janela.mudarTela(new TelaAdicionarFranquia(sistema, usuario, janela));
    }//GEN-LAST:event_adicionarFranquiaButtonActionPerformed

    private void editarFranquiaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarFranquiaButtonActionPerformed
        if (franquiasList.getSelectedValue() == null) return;
        
        janela.mudarTela(new TelaEditarFranquia(sistema, usuario, janela, franquiasList.getSelectedValue()));
    }//GEN-LAST:event_editarFranquiaButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adicionarFranquiaButton;
    private javax.swing.JButton adicionarGerenteButton;
    private javax.swing.JButton editarFranquiaButton;
    private javax.swing.JButton editarGerenteButton;
    private javax.swing.JButton excluirFranquiaButton;
    private javax.swing.JButton excluirGerenteButton;
    private javax.swing.JLabel franquiasLabel;
    private javax.swing.JList<Franquia> franquiasList;
    private javax.swing.JPanel franquiasPanel;
    private javax.swing.JScrollPane franquiasScroll;
    private javax.swing.JLabel gerentesLabel;
    private javax.swing.JList<Gerente> gerentesList;
    private javax.swing.JPanel gerentesPanel;
    private javax.swing.JScrollPane gerentesScroll;
    private javax.swing.JPanel informacoesPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel logadoComoLabel;
    private javax.swing.JLabel nomeUsuarioLabel;
    private javax.swing.JButton visualizarFranquiaButton;
    // End of variables declaration//GEN-END:variables
}
