/*
 * Alex Sandro de Macedo Pinto
 * 202465551C
 */
package com.alex.dcc025.gui.tela.login;

import com.alex.dcc025.Sistema;
import com.alex.dcc025.gui.GUI;
import com.alex.dcc025.gui.tela.dono.TelaDono;
import com.alex.dcc025.gui.tela.gerente.TelaGerente;
import com.alex.dcc025.gui.tela.vendedor.TelaVendedor;
import com.alex.dcc025.usuario.Usuario;
import com.alex.dcc025.usuario.usuario.Dono;
import com.alex.dcc025.usuario.usuario.Gerente;
import com.alex.dcc025.usuario.usuario.Vendedor;

import javax.swing.JOptionPane;

/**
 *
 * @author SUPERVISOR
 */
public class TelaLogin extends javax.swing.JPanel {

    private final Sistema sistema;
    private final GUI janela;
    
    /**
     * Creates new form TelaLogin
     */
    public TelaLogin(Sistema sistema, GUI janela) {
        this.sistema = sistema;
        this.janela = janela;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        containerGrande = new javax.swing.JPanel();
        usuarioContainer = new javax.swing.JPanel();
        usuarioField = new javax.swing.JTextField();
        usuarioLabel = new javax.swing.JLabel();
        senhaContainer = new javax.swing.JPanel();
        senhaField = new javax.swing.JPasswordField();
        senhaLabel = new javax.swing.JLabel();
        entrarButton = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(1280, 720));

        containerGrande.setPreferredSize(new java.awt.Dimension(270, 170));

        usuarioContainer.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        usuarioField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usuarioFieldActionPerformed(evt);
            }
        });

        usuarioLabel.setText("Usuário");

        javax.swing.GroupLayout usuarioContainerLayout = new javax.swing.GroupLayout(usuarioContainer);
        usuarioContainer.setLayout(usuarioContainerLayout);
        usuarioContainerLayout.setHorizontalGroup(
            usuarioContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, usuarioContainerLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(usuarioField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(usuarioContainerLayout.createSequentialGroup()
                .addComponent(usuarioLabel)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        usuarioContainerLayout.setVerticalGroup(
            usuarioContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usuarioContainerLayout.createSequentialGroup()
                .addComponent(usuarioLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(usuarioField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        senhaContainer.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        senhaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaFieldActionPerformed(evt);
            }
        });

        senhaLabel.setText("Senha");

        javax.swing.GroupLayout senhaContainerLayout = new javax.swing.GroupLayout(senhaContainer);
        senhaContainer.setLayout(senhaContainerLayout);
        senhaContainerLayout.setHorizontalGroup(
            senhaContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(senhaContainerLayout.createSequentialGroup()
                .addComponent(senhaLabel)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(senhaContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(senhaField, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                .addContainerGap())
        );
        senhaContainerLayout.setVerticalGroup(
            senhaContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, senhaContainerLayout.createSequentialGroup()
                .addComponent(senhaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(senhaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        entrarButton.setText("Entrar");
        entrarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                entrarButtonMouseClicked(evt);
            }
        });
        entrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout containerGrandeLayout = new javax.swing.GroupLayout(containerGrande);
        containerGrande.setLayout(containerGrandeLayout);
        containerGrandeLayout.setHorizontalGroup(
            containerGrandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerGrandeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(containerGrandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(entrarButton)
                    .addGroup(containerGrandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(usuarioContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(senhaContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(52, 52, 52))
        );
        containerGrandeLayout.setVerticalGroup(
            containerGrandeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, containerGrandeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(usuarioContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(senhaContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(entrarButton)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(530, Short.MAX_VALUE)
                .addComponent(containerGrande, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(511, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(275, Short.MAX_VALUE)
                .addComponent(containerGrande, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(275, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void usuarioFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usuarioFieldActionPerformed

    }//GEN-LAST:event_usuarioFieldActionPerformed

    private void senhaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaFieldActionPerformed

    private void entrarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_entrarButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_entrarButtonMouseClicked

    private void entrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrarButtonActionPerformed
        Usuario usuario = sistema.login(usuarioField.getText().trim(), new String(senhaField.getPassword()));
        
        if (usuario == null) {
            JOptionPane.showMessageDialog(null, "Falha no login");
            senhaField.setText("");
            return;
        }
        
        switch (usuario.getTipo()) {
            case 0 -> janela.mudarTela(new TelaDono(sistema, (Dono) usuario, janela));
            case 1 -> {
                
                Gerente gerente = (Gerente) usuario;

                if (gerente.getFranquia() == null) {
                    JOptionPane.showMessageDialog(null, "Gerente deve ter uma franquia associada.");
                    senhaField.setText("");
                    return;
                }

                janela.mudarTela(new TelaGerente(sistema, gerente, janela));
            }
            case 2 -> janela.mudarTela(new TelaVendedor(sistema, (Vendedor) usuario, janela));
        }

        senhaField.setText("");
    }//GEN-LAST:event_entrarButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel containerGrande;
    private javax.swing.JButton entrarButton;
    private javax.swing.JPanel senhaContainer;
    private javax.swing.JPasswordField senhaField;
    private javax.swing.JLabel senhaLabel;
    private javax.swing.JPanel usuarioContainer;
    private javax.swing.JTextField usuarioField;
    private javax.swing.JLabel usuarioLabel;
    // End of variables declaration//GEN-END:variables
}
